before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY


build_image:
  script:
    - docker-compose -f docker-compose.yml build
  stage: build_image
  tags:
    - shell
  
push_image:
  script:
    - docker-compose -f docker-compose.yml push
  stage: push_image
  tags:
    - shell

# deploy:
#   - docker stack deploy -c docker-compose.yml writer
#   tags:
#     - shell

stages:
  - build_image
  - push_image
  # - deploy

