variables:
  GIT_SUBMODULE_STRATEGY: recursive


before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY


build_image:
  script:
    - export TAG="${CI_BUILD_REF_NAME}"
    - docker-compose -f docker-compose.yml build
  stage: build_image
  tags:
    - shell
    - pm01
  only:
    - tags
    - triggers
  
push_image:
  script:
    - export TAG="${CI_BUILD_REF_NAME}"
    - docker-compose -f docker-compose.yml push
  stage: push_image
  tags:
    - shell
    - pm01
  only:
    - tags
    - triggers

deploy:
  script:
    - export TAG="${CI_BUILD_REF_NAME}"
    - docker stack deploy -c docker-compose.yml writer
  stage: deploy
  tags:
    - shell
    - pm01
  only:
    - tags
    - triggers


stages:
  - build_image
  - push_image
  - deploy
