version: "3.4"

services:
  writer:
    image: 'writer:${TAG-latest}'
    build:
      context: ./writer
      target: development
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
      - HBASE_HOSTNAME=hbase
      - ES_URL=elasticsearch
      - LOG_LEVEL=DEBUG
    volumes:
      - ./writer:/usr/src/app/

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'

  rabbitmq:
    image: 'rabbitmq:3.7-management-alpine'
    ports:
      - 15672:15672
      - 5672:5672

  hbase:
    image: 'jonatasbaldin/hbase-standalone'
    ports:
      - '8080:8080'
      - '8085:8085'
      - '9090:9090'
      - '16010:16010'
      - '16020:16020'
      - '16030:16030'
